import type { MarketplaceSourceListing } from "@/types/marketplace";

const now = Date.now();

function hoursAgo(hours: number) {
  return new Date(now - hours * 60 * 60 * 1000).toISOString();
}

export const demoMarketplaceListings: MarketplaceSourceListing[] = [
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-001",
    title: "Milwaukee M18 Fuel hammer drill kit with battery and charger",
    description: "Used on two jobs. Includes hard case, XC battery, charger, side handle, and bit set. Works perfectly.",
    price: 95,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/mkt-001",
    imageUrls: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(2),
    sellerName: "Marcus",
    conditionRaw: "used - good",
    metadata: { category: "power tools", brand: "Milwaukee", model: "M18 Fuel 2804-20", includes: ["battery", "charger", "case"], stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-002",
    title: "Milwaukee M18 Fuel hammer drill bare tool",
    description: "Bare tool only. Moderate wear but tested and strong.",
    price: 139,
    currency: "USD",
    location: "Plano, TX",
    url: "https://example.com/demo/mkt-002",
    imageUrls: ["https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(10),
    sellerName: "Tool Outlet",
    conditionRaw: "used - fair",
    metadata: { category: "power tools", brand: "Milwaukee", model: "M18 Fuel 2804-20", includes: ["tool"], stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-003",
    title: "DeWalt 20V Max XR impact driver with two batteries",
    description: "Clean set. Batteries still strong. Charger included.",
    price: 125,
    currency: "USD",
    location: "Fort Worth, TX",
    url: "https://example.com/demo/mkt-003",
    imageUrls: ["https://images.unsplash.com/photo-1563198804-1f7d28640a3d?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(6),
    sellerName: "Chris",
    conditionRaw: "used - good",
    metadata: { category: "power tools", brand: "DeWalt", model: "DCF887", includes: ["tool", "battery", "battery", "charger"], stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-004",
    title: "Sony A6400 camera body only",
    description: "Shutter count under 9k. Excellent shape, one small mark on bottom plate.",
    price: 645,
    currency: "USD",
    location: "Austin, TX",
    url: "https://example.com/demo/mkt-004",
    imageUrls: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(16),
    sellerName: "Natalie",
    conditionRaw: "used - like new",
    metadata: { category: "cameras", brand: "Sony", model: "A6400", includes: ["body", "strap", "battery"], stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-005",
    title: "Sony a6400 with 16-50 lens and extra battery",
    description: "Ready to shoot. Includes box and kit lens.",
    price: 780,
    currency: "USD",
    location: "Houston, TX",
    url: "https://example.com/demo/mkt-005",
    imageUrls: ["https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(20),
    sellerName: "Lena",
    conditionRaw: "used - good",
    metadata: { category: "cameras", brand: "Sony", model: "A6400", includes: ["body", "16-50 lens", "battery", "battery"], stockPhotoOnly: false }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-101",
    title: "Milwaukee M18 FUEL hammer drill + xc5.0 battery",
    description: "Very clean. Only selling because I switched brands.",
    price: 155,
    currency: "USD",
    location: "Irving, TX",
    url: "https://example.com/demo/ccd-101",
    imageUrls: ["https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(9),
    sellerName: "N. Diaz",
    conditionRaw: "used - good",
    metadata: { category: "power tools", brand: "Milwaukee", model: "M18 Fuel 2804-20", includes: ["tool", "battery"], stockPhotoOnly: false }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-102",
    title: "Milwaukee 2804 M18 Fuel hammer drill tool only",
    description: "Heavy cosmetic wear. Works. No battery. No charger.",
    price: 84,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/ccd-102",
    imageUrls: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(1),
    sellerName: "Jose",
    conditionRaw: "used - fair",
    metadata: { category: "power tools", brand: "Milwaukee", model: "2804-20", includes: ["tool"], stockPhotoOnly: false }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-103",
    title: "Milwaukee hammer drill looks new stock photo",
    description: "New in box maybe? Message for details.",
    price: 60,
    currency: "USD",
    location: "Mesquite, TX",
    url: "https://example.com/demo/ccd-103",
    imageUrls: ["https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(3),
    sellerName: "Seller123",
    conditionRaw: "unknown",
    metadata: { category: "power tools", brand: "Milwaukee", model: "", includes: [], stockPhotoOnly: true }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-104",
    title: "Sony Alpha a6400 mirrorless camera body",
    description: "Body cap, battery, strap. Minor signs of use. Great autofocus.",
    price: 699,
    currency: "USD",
    location: "Garland, TX",
    url: "https://example.com/demo/ccd-104",
    imageUrls: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(8),
    sellerName: "Victor",
    conditionRaw: "used - good",
    metadata: { category: "cameras", brand: "Sony", model: "A6400", includes: ["body", "battery", "strap"], stockPhotoOnly: false }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-105",
    title: "Canon R50 mirrorless kit like new",
    description: "Barely used. Box included.",
    price: 610,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/ccd-105",
    imageUrls: ["https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(14),
    sellerName: "Jamil",
    conditionRaw: "used - like new",
    metadata: { category: "cameras", brand: "Canon", model: "R50", includes: ["body", "kit lens", "box"], stockPhotoOnly: false }
  },
  {
    source: "estate_finds_demo",
    sourceListingId: "efd-201",
    title: "Apple MacBook Air 13 M2 8GB 256GB midnight",
    description: "Battery health 98%. Includes charger. Tiny nick on lid edge.",
    price: 760,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/efd-201",
    imageUrls: ["https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(5),
    sellerName: "Ari",
    conditionRaw: "used - good",
    metadata: { category: "laptops", brand: "Apple", model: "MacBook Air M2", specs: { ram: "8GB", storage: "256GB" }, stockPhotoOnly: false }
  },
  {
    source: "estate_finds_demo",
    sourceListingId: "efd-202",
    title: "MacBook Air M2 13-inch 256gb",
    description: "Works great. Charger included. Fast pickup only.",
    price: 720,
    currency: "USD",
    location: "Arlington, TX",
    url: "https://example.com/demo/efd-202",
    imageUrls: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(11),
    sellerName: "T. Quinn",
    conditionRaw: "used - good",
    metadata: { category: "laptops", brand: "Apple", model: "MacBook Air M2", specs: { ram: "8GB", storage: "256GB" }, stockPhotoOnly: false }
  },
  {
    source: "estate_finds_demo",
    sourceListingId: "efd-203",
    title: "Apple MacBook Air M2 for parts cracked screen",
    description: "Turns on but screen cracked badly. Good board/battery for repair.",
    price: 320,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/efd-203",
    imageUrls: ["https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(18),
    sellerName: "Repair Hub",
    conditionRaw: "for parts",
    metadata: { category: "laptops", brand: "Apple", model: "MacBook Air M2", damage: "screen", stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-006",
    title: "Apple MacBook Air M2 13 midnight 8/256 with AppleCare",
    description: "AppleCare through November. Excellent condition.",
    price: 890,
    currency: "USD",
    location: "Frisco, TX",
    url: "https://example.com/demo/mkt-006",
    imageUrls: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(7),
    sellerName: "Sarah",
    conditionRaw: "used - like new",
    metadata: { category: "laptops", brand: "Apple", model: "MacBook Air M2", includes: ["charger", "AppleCare"], stockPhotoOnly: false }
  },
  {
    source: "community_classifieds_demo",
    sourceListingId: "ccd-106",
    title: "Sony A6400 body only bargain",
    description: "No charger. Camera works. Need gone today.",
    price: 520,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/ccd-106",
    imageUrls: ["https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(1),
    sellerName: "Quick Sale",
    conditionRaw: "used - fair",
    metadata: { category: "cameras", brand: "Sony", model: "A6400", includes: ["body"], stockPhotoOnly: false }
  },
  {
    source: "estate_finds_demo",
    sourceListingId: "efd-204",
    title: "Milwaukee M18 Fuel drill driver 2804 with charger",
    description: "Good running drill, charger only, no battery.",
    price: 118,
    currency: "USD",
    location: "Richardson, TX",
    url: "https://example.com/demo/efd-204",
    imageUrls: ["https://images.unsplash.com/photo-1581094288338-2314dddb7ece?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(13),
    sellerName: "Brad",
    conditionRaw: "used - good",
    metadata: { category: "power tools", brand: "Milwaukee", model: "2804-20", includes: ["tool", "charger"], stockPhotoOnly: false }
  },
  {
    source: "marketplace_demo_feed",
    sourceListingId: "mkt-007",
    title: "Apple MacBook Air M2 8gb 256gb",
    description: "Basic M2 Air. Charger. One dent on corner.",
    price: 680,
    currency: "USD",
    location: "Dallas, TX",
    url: "https://example.com/demo/mkt-007",
    imageUrls: ["https://images.unsplash.com/photo-1517336714739-489689fd1ca8?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(2),
    sellerName: "Elijah",
    conditionRaw: "used - fair",
    metadata: { category: "laptops", brand: "Apple", model: "MacBook Air M2", includes: ["charger"], stockPhotoOnly: false }
  },
  {
    source: "estate_finds_demo",
    sourceListingId: "efd-205",
    title: "Makita drill combo set",
    description: "Hammer drill and impact driver with case. Not Milwaukee.",
    price: 110,
    currency: "USD",
    location: "Denton, TX",
    url: "https://example.com/demo/efd-205",
    imageUrls: ["https://images.unsplash.com/photo-1563198804-1f7d28640a3d?auto=format&fit=crop&w=900&q=80"],
    postedAt: hoursAgo(12),
    sellerName: "Pete",
    conditionRaw: "used - good",
    metadata: { category: "power tools", brand: "Makita", model: "XT269M", stockPhotoOnly: false }
  }
];
